# SELECT datetime( (request_start_date/1000), 'unixepoch','localtime') , datetime( (request_required_for_date/1000), 'unixepoch','localtime')  from request

# --- !Ups

create table "USER" (
"USER_ID" INTEGER PRIMARY KEY,
"USER_NAME" VARCHAR NOT NULL,
"USER_PASSWORD" VARCHAR NOT NULL,
"USER_HANDLE" VARCHAR NOT NULL
);


create table "PROJECT" (
"PROJECT_ID" INTEGER PRIMARY KEY,
"PROJECT_START_DATE" TIMESTAMP,
"PROJECT_END_DATE" TIMESTAMP,
"PROJECT_CODE" VARCHAR ,
"PROJECT_NAME" VARCHAR 
);

create table "RECORDWORK" (
"RECORDWORK_ID" INTEGER PRIMARY KEY,
"RECORDWORK_USER_ID" INTEGER ,
"RECORDWORK_START_DATE" TIMESTAMP NOT NULL,
"RECORDWORK_PROJECT_ID" INTEGER NOT NULL,
"RECORDWORK_EFFORT" REAL NOT NULL,
 FOREIGN KEY("RECORDWORK_PROJECT_ID") REFERENCES "PROJECT"("PROJECT_ID"),
 FOREIGN KEY("RECORDWORK_USER_ID") REFERENCES "USER"("USER_ID")
);


insert into "USER" ("USER_NAME","USER_PASSWORD","USER_HANDLE") VALUES ("bernard","jason","bernie");
insert into "USER" ("USER_NAME","USER_PASSWORD","USER_HANDLE") VALUES ("tea","mug","big tea");
insert into "USER" ("USER_ID","USER_NAME","USER_PASSWORD","USER_HANDLE") VALUES (1,'bernard','jason','bernie');

INSERT INTO PROJECT VALUES(1,NULL,NULL,'LEAV001','Holiday');
INSERT INTO PROJECT VALUES(2,NULL,NULL,'LEAV002','Sick');
INSERT INTO PROJECT VALUES(3,NULL,NULL,'BUG1o1','Bug fixes');
INSERT INTO PROJECT VALUES(4,NULL,NULL,'TRACK01','Tracker demo');

INSERT INTO RECORDWORK VALUES(1,1,1535929200000,4,37.5);
INSERT INTO RECORDWORK VALUES(2,1,1536534000000,2,30.0);
INSERT INTO RECORDWORK VALUES(3,1,1536534000000,4,7.5);
INSERT INTO RECORDWORK VALUES(4,2,1536534000000,4,37.5);
INSERT INTO RECORDWORK VALUES(5,2,1535929200000,0,0.0);


# --- !Downs

drop table "RECORDWORK";
drop table "PROJECT";
drop table "USER";
