

drop table "RECORDWORK";
drop table "PROJECT";
drop table "USER";

create table "USER" (
"USER_ID" SERIAL PRIMARY KEY,
"USER_NAME" VARCHAR NOT NULL,
"USER_PASSWORD" VARCHAR NOT NULL,
"USER_HANDLE" VARCHAR NOT NULL
);

create table "PROJECT" (
"PROJECT_ID" SERIAL PRIMARY KEY,
"PROJECT_START_DATE" TIMESTAMP,
"PROJECT_END_DATE" TIMESTAMP,
"PROJECT_CODE" VARCHAR ,
"PROJECT_NAME" VARCHAR 
);

create table "RECORDWORK" (
"RECORDWORK_ID" SERIAL PRIMARY KEY,
"RECORDWORK_USER_ID" INTEGER ,
"RECORDWORK_START_DATE" TIMESTAMP NOT NULL,
"RECORDWORK_PROJECT_ID" INTEGER NOT NULL,
"RECORDWORK_EFFORT" REAL NOT NULL,
 FOREIGN KEY("RECORDWORK_PROJECT_ID") REFERENCES "PROJECT"("PROJECT_ID"),
 FOREIGN KEY("RECORDWORK_USER_ID") REFERENCES "USER"("USER_ID")
);

insert into "USER" ("USER_NAME","USER_PASSWORD","USER_HANDLE") VALUES ('bernard','jason','bernie');
insert into "USER" ("USER_NAME","USER_PASSWORD","USER_HANDLE") VALUES ('tea','mug','big tea');

